G$TM$Status$JVM$CPU$load=Gauge
G$TM$Status$JVM$CPU$time=Gauge
G$TM$Status$JVM$Memory$Heap$Used=Gauge
G$TM$Status$JVM$Memory$Heap$Committed=Gauge
G$TM$Status$JVM$Memory$Heap$Max=Gauge
G$TM$Status$JVM$Memory$NonHeap$Used=Gauge
G$TM$Status$JVM$Memory$Direct$Count=Gauge
G$TM$Status$Flink$Memory$Managed$Used=Gauge
G$TM$Status$Flink$Memory$Managed$Total=Gauge
G$TM$Status$Status$JVM$Threads$Count=Gauge
G$TM$Status$JVM$ClassLoader$ClassesLoaded=Gauge
G$TM$Status$JVM$ClassLoader$ClassesUnLoaded=Gauge
G$TM$Status$Network$AvailableMemorySegments=Gauge
G$TM$Status$Network$TotalMemorySegments=Gauge
G$TM$Status$Shuffle$Netty$AvailableMemorySegments=Gauge
G$TM$Status$Shuffle$Netty$UsedMemorySegments=Gauge
G$TM$Status$Shuffle$Netty$TotalMemorySegments=Gauge
G$TM$Status$Shuffle$Netty$AvailableMemory=Gauge
G$TM$Status$Shuffle$Netty$UsedMemory=Gauge
G$TM$Status$Shuffle$Netty$TotalMemory=Gauge
C$TM_JOB$ChangelogStorage.numberOfUploadRequests=Counter
C$TM_JOB$ChangelogStorage.numberOfUploadFailures=Counter
H$TM_JOB$ChangelogStorage.attemptsPerUpload=Histogram
C$TM_JOB$ChangelogStorage.uploadQueueSize=Gauge
H$OPERATOR$sample_operator_id$sample_operator$0$stateClearLatency=Histogram
H$OPERATOR$sample_operator_id$sample_operator$0$aggregatingStateGetLatency=Histogram
C$OPERATOR$sample_operator_id$sample_operator$0$numRecordsIn=Counter
M$OPERATOR$sample_operator_id$sample_operator$0$numRecordsInPerSecond=Meter
C$OPERATOR$sample_operator_id$sample_operator$0$numRecordsOut=Counter
M$OPERATOR$sample_operator_id$sample_operator$0$numRecordsOutPerSecond=Meter
C$OPERATOR$sample_operator_id$sample_operator$0$numLateRecordsDropped=Counter
G$OPERATOR$sample_operator_id$sample_operator$0$currentInputWatermark=Gauge
G$OPERATOR$sample_operator_id$sample_operator$0$currentOutputWatermark=Gauge
G$OPERATOR$sample_operator_id$sample_operator$0$watermarkAlignmentDrift=Gauge
G$OPERATOR$sample_operator_id$sample_operator$0$numSplitsProcessed=Gauge
G$TASK$sample_task$0$buffers$inputQueueLength=Gauge
G$TASK$sample_task$0$buffers$outputQueueLength=Gauge
G$TASK$sample_task$0$buffers$inPoolUsage=Gauge
G$TASK$sample_task$0$buffers$outPoolUsage=Gauge
G$TASK$sample_task$0$buffers$inputFloatingBuffersUsage=Gauge
G$TASK$sample_task$0$Shuffle$Netty$Input$Buffers$inputQueueLength=Gauge
G$TASK$sample_task$0$Shuffle$Netty$Input$Buffers$inputQueueSize=Gauge
G$TASK$sample_task$0$Shuffle$Netty$Input$Buffers$inPoolUsage=Gauge
G$TASK$sample_task$0$Shuffle$Netty$Input$Buffers$inputFloatingBuffersUsage=Gauge
G$TASK$sample_task$0$Shuffle$Netty$Output$Buffers$outputQueueLength=Gauge
G$TASK$sample_task$0$Shuffle$Netty$Output$Buffers$outputQueueSize=Gauge
G$TASK$sample_task$0$Shuffle$Netty$Output$Buffers$outPoolUsage=Gauge
C$TASK$sample_task$0$Shuffle$Netty$Input$numBytesInLocal=Counter
M$TASK$sample_task$0$Shuffle$Netty$Input$numBytesInLocalPerSecond=Meter
C$TASK$sample_task$0$Shuffle$Netty$numBytesInRemote=Counter
M$TASK$sample_task$0$Shuffle$Netty$Input$numBytesInRemotePerSecond=Meter
C$TASK$sample_task$0$Shuffle$Netty$Input$numBuffersInLocal=Counter
M$TASK$sample_task$0$Shuffle$Netty$Input$numBuffersInLocalPerSecond=Meter
C$TASK$sample_task$0$Shuffle$Netty$Input$numBuffersInRemote=Counter
M$TASK$sample_task$0$Shuffle$Netty$Input$numBuffersInRemotePerSecond=Meter
G$TASK$sample_task$0$checkpointAlignmentTime=Gauge
G$TASK$sample_task$0$checkpointStartDelayNanos=Gauge
H$TASK$sample_task$0$stateClearLatency=Histogram
H$TASK$sample_task$0$aggregatingStateGetLatency=Histogram
C$TASK$sample_task$0$numBytesOut=Counter
M$TASK$sample_task$0$numBytesOutPerSecond=Meter
C$TASK$sample_task$0$numBuffersOut=Counter
M$TASK$sample_task$0$numBuffersOutPerSecond=Meter
G$TASK$sample_task$0$isBackPressured=Gauge
C$TASK$sample_task$0$numRecordsIn=Counter
M$TASK$sample_task$0$numRecordsInPerSecond=Meter
C$TASK$sample_task$0$numRecordsOut=Counter
M$TASK$sample_task$0$numRecordsOutPerSecond=Meter
C$TASK$sample_task$0$numLateRecordsDropped=Counter
G$TASK$sample_task$0$currentInputWatermark=Gauge
